function [MOVINGREG] = registerImagesSIM(MOVING,FIXED,movingpoints,fixedpoints)
%registerImages  Register grayscale images using auto-generated code from Registration Estimator app.
%  [MOVINGREG] = registerImages(MOVING,FIXED) Register grayscale images
%  MOVING and FIXED using auto-generated code from the Registration
%  Estimator app. The values for all registration parameters were set
%  interactively in the app and result in the registered image stored in the
%  structure array MOVINGREG.

% Auto-generated by registrationEstimator app on 22-Nov-2021
%-----------------------------------------------------------


% Feature-based techniques require license to Computer Vision Toolbox
checkLicense()

% Normalize MOVING image

% Get linear indices to finite valued data
finiteIdx = isfinite(MOVING(:));

% Replace NaN values with 0
MOVING(isnan(MOVING)) = 0;

% Replace Inf values with 1
MOVING(MOVING==Inf) = 1;

% Replace -Inf values with 0
MOVING(MOVING==-Inf) = 0;

% Normalize input data to range in [0,1].
MOVINGmin = min(MOVING(:));
MOVINGmax = max(MOVING(:));
if isequal(MOVINGmax,MOVINGmin)
    MOVING = 0*MOVING;
else
    MOVING(finiteIdx) = (MOVING(finiteIdx) - MOVINGmin) ./ (MOVINGmax - MOVINGmin);
end

% Default spatial referencing objects
fixedRefObj = imref2d(size(FIXED));
movingRefObj = imref2d(size(MOVING));

% Detect SURF features
% fixedPoints = detectSURFFeatures(FIXED,'MetricThreshold',500.000000,'NumOctaves',4,'NumScaleLevels',6);
% movingPoints = detectSURFFeatures(MOVING,'MetricThreshold',500.000000,'NumOctaves',4,'NumScaleLevels',6);

% % Extract features
% [fixedFeatures,fixedValidPoints] = extractFeatures(FIXED,fixedpoints,'Upright',true);
% [movingFeatures,movingValidPoints] = extractFeatures(MOVING,movingpoints,'Upright',true);

% Match features
% indexPairs = matchFeatures(fixedFeatures,movingFeatures,'MatchThreshold',18.499985,'MaxRatio',0.185000);
% fixedMatchedPoints = fixedValidPoints(indexPairs(:,1));
% movingMatchedPoints = movingValidPoints(indexPairs(:,2));
% MOVINGREG.FixedMatchedFeatures = fixedMatchedPoints;
% MOVINGREG.MovingMatchedFeatures = movingMatchedPoints;

% Apply transformation - Results may not be identical between runs because of the randomized nature of the algorithm
[tform,inlieridx] = estimateGeometricTransform2D(movingpoints,fixedpoints,'affine');
MOVINGREG.Transformation = tform;
MOVINGREG.RegisteredImage = imwarp(MOVING, movingRefObj, tform, 'OutputView', fixedRefObj, 'SmoothEdges', true);

% Store spatial referencing object
MOVINGREG.SpatialRefObj = fixedRefObj;
MOVINGREG.inlierIdx = inlieridx;
end

function checkLicense()

% Check for license to Computer Vision Toolbox
CVTStatus = license('test','Video_and_Image_Blockset');
if ~CVTStatus
    error(message('images:imageRegistration:CVTRequired'));
end

end

